/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) throws InterruptedException {
        System.out.println("Hellow World");
        Scanner sc = new Scanner(System.in);
        boolean flag = true;
        while(flag){
            System.out.println("1->b\n2->c\n3->a\n4->bt\n5->e");
            int opt = sc.nextInt();
            Ticket t = new Ticket();
            String name = "";
            int age = -1;
            switch (opt){
                case 1:
                    sc.nextLine();
                    name = sc.nextLine();
                    System.out.println(name);
                    // sc.nextLine();
                    age = sc.nextInt();
                    System.out.println(age);
                    int birthPreference = sc.nextInt();
                    System.out.println(birthPreference);
                    Passenger p = new Passenger(name, age, birthPreference);
                    t.book(p);
                    System.out.println(p.getAlloted());
                    sc.nextLine();
                    break;

                case 2:
                    int id = sc.nextInt();
                    sc.nextLine();
                    name = sc.nextLine();
                    age = sc.nextInt();
                    Passenger pc = new Passenger(id, name, age);
                    t.Cancel(pc);
                case 3:
                    t.Available();
                    //break;

                case 4:
                    t.Booked();
                    break;

                case 5:
                    flag = false;
                    break;
            }
        }
        sc.close();
    }
}

